services: 

  audit-app:
    build: ./audit
    command: python app.py
    networks:
      - backend
    volumes:
      - ./audit/src:/code
    ports:
      - "5000:5000"
    expose:
      - "5000"


networks:
  backend:
  frontend:

volumes:
    sender-app: 
