services:

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  backend:
    build: ./backend
    # command: python -m http.server -d /code 8001
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      - ./backend/src:/code
    depends_on:
      db:
        condition: service_started
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=rootpassword

networks:
  backend:

volumes:
  mongo-data: