# Generated by Django 4.0.1 on 2024-07-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('holder', 'Holder'), ('admin', 'Admin'), ('consumer', 'Consumer')], default='holder', max_length=10),
        ),
    ]
