# Generated by Django 4.0.1 on 2024-07-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(max_length=1000000000, primary_key=True, serialize=False, unique=True),
        ),
    ]
