services:

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  backend:
    build: ./backend
    networks:
      - backend
    depends_on:
      db:
        condition: service_started

  auditoria:
    build: ./auditoria
    networks:
      - backend

  web:
    build: ./django
    # command: python -m http.server -d /code/static 8000
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - frontend
      - backend
    volumes:
      - ./src:/code
    depends_on:
      backend:
        condition: service_started
      auditoria:
        condition: service_started
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=rootpassword



networks:
  backend:
  frontend:


volumes:
  mongo-data: